variables:
- name: 'environment'
  value: 'PRD'
- name: 'terraform_folder'
  value: 'projects'
- name: 'artifact_name'
  value: 'projects'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: "CopyFiles"
    steps:    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/$(terraform_folder)'
      inputs:
        SourceFolder: $(terraform_folder)
        TargetFolder: '$(build.artifactstagingdirectory)/$(terraform_folder)'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: $(artifact_name)'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: $(artifact_name)

- stage: Terraform_Plan
  jobs:
  - job: "Terraform_Plan"
    steps:
      - checkout: none
        clean: true
        fetchDepth: 5
        lfs: true
        
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: '$(artifact_name)'
          downloadPath: '$(System.DefaultWorkingDirectory)'
        displayName: 'Download Artifact'

      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.2.2'
        displayName: 'Install Terraform'
        
      - script: |
          terraform init -backend-config="key=$(backend_key)"
        workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
        displayName: 'Terraform Init'
                     
      - script: |
          terraform plan
        workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
        displayName: 'Terraform Plan'
        
- stage: deploy
  jobs:
    - deployment: DeployTerraform
      displayName: Deploy to Azure
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
                clean: true
                fetchDepth: 5
                lfs: true

              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: '$(artifact_name)'
                  downloadPath: '$(System.DefaultWorkingDirectory)'
                displayName: 'Download Artifact'

              - task: TerraformInstaller@0
                inputs:
                  terraformVersion: '1.2.2'
                displayName: 'Install Terraform'

              - script: |
                  terraform init -backend-config="key=$(backend_key)"
                workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
                displayName: 'Terraform Init'
                                
              - script: |
                  terraform apply -auto-approve
                workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
                displayName: 'Terraform Apply'

